siteName: Ewell Roofing
author: David White
poweredBy: Kabooly
poweredByUrl: https://kabooly.com
email: something@ewell-roofing.co.uk
phoneNumber: "0000 000 0000"
companyNumber: "123456789"
addressLineOne: Address Line 1
addressLineTwo: Address line 2
addressLineThree: Address Line 3
townCity: Town
region: London
postCode: 000 000
locationLatLong: 
country: "GB"
googleOpeningMonday: "14:00"
googleClosingMonday: "19:30"
googleOpeningTuesday: "08:00"
googleClosingTuesday: "13:00"
googleOpeningWednesday: "08:00"
googleClosingWednesday: "13:00"
googleOpeningThursday: "14:00"
googleClosingThursday: "19:30"
googleOpeningFriday: "08:00"
googleClosingFriday: "11:00"
googleOpeningSaturday: "09:00"
googleClosingSaturday: "12:00"
